from .appointment_admin import AppointmentAdmin
from .base_risk_assessment_admin import BaseRiskAssessmentAdmin
from .base_risk_assessment_alcohol_admin import BaseRiskAssessmentAlcoholAdmin
from .base_risk_assessment_cancer_admin import BaseRiskAssessmentCancerAdmin
from .base_risk_assessment_chemical_admin import BaseRiskAssessmentChemicalAdmin
from .base_risk_assessment_demo_admin import BaseRiskAssessmentDemoAdmin
from .base_risk_assessment_eating_admin import BaseRiskAssessmentEatingAdmin
from .base_risk_assessment_female_admin import BaseRiskAssessmentFemaleAdmin
from .base_risk_assessment_fuel_admin import BaseRiskAssessmentFuelAdmin
from .base_risk_assessment_mining_admin import BaseRiskAssessmentMiningAdmin
from .base_risk_assessment_smoking_admin import BaseRiskAssessmentSmokingAdmin
from .base_risk_assessment_sun_admin import BaseRiskAssessmentSunAdmin
from .baseline_hiv_history_admin import BHHWhoIllnessAdmin, BHHCd4Admin
from .baseline_hiv_history_admin import BaselineHIVHistoryAdmin, BHHHivTestAdmin
from .enrollment_checklist_admin import EnrollmentChecklistAdmin
# from .lab_result_admin import LabResultAdmin, LabResultHeightWeightAdmin
# from .lab_result_admin import LabResultHivAdmin, LabResultCd4Admin, LabResultViralloadAdmin
# from .lab_result_admin import LabResultHaematologyAdmin, LabResultChemistryAdmin
# from .lab_result_admin import LabResultTbAdmin
# from .main import ActivityAndFunctioningAdmin, CancerDiagnosisAdmin
# from .main import HaartRecordAdmin, OncologyTreatmentPlanAdmin, TreatmentResponseAdmin
# from .main import SymptomsAndTestingAdmin, OncologyTreatmentCompletedAdmin
# from .main import CurrentSymptomsAdmin
# from .oncology_treatment_record_admin import OncologyTreatmentRecordAdmin, OTRChemoAdmin
# from .oncology_treatment_record_admin import OTRRadiationAdmin, OTRSurgicalAdmin
from .radiation_treatment_admin import RadiationTreatmentAdmin
from .subject_consent_admin import SubjectConsentAdmin
from .subject_locator_admin import SubjectLocatorAdmin
from .subject_visit_admin import SubjectVisitAdmin
