# from .appointment_admin import AppointmentAdmin
from .base_risk_assessment_admin import BaseRiskAssessmentAdmin
from .base_risk_assessment_alcohol_admin import BaseRiskAssessmentAlcoholAdmin
from .base_risk_assessment_cancer_admin import BaseRiskAssessmentCancerAdmin
from .base_risk_assessment_chemical_admin import BaseRiskAssessmentChemicalAdmin
from .base_risk_assessment_demo_admin import BaseRiskAssessmentDemoAdmin
from .base_risk_assessment_eating_admin import BaseRiskAssessmentEatingAdmin
from .base_risk_assessment_female_admin import BaseRiskAssessmentFemaleAdmin
from .base_risk_assessment_fuel_admin import BaseRiskAssessmentFuelAdmin
from .base_risk_assessment_mining_admin import BaseRiskAssessmentMiningAdmin
from .base_risk_assessment_smoking_admin import BaseRiskAssessmentSmokingAdmin
from .base_risk_assessment_sun_admin import BaseRiskAssessmentSunAdmin
from .baseline_hiv_history_admin import BaselineHIVHistoryAdmin
from .bhh_cd4_admin import BHHCd4Admin
from .bhh_hiv_test_admin import BHHHivTestAdmin
from .bhh_who_illness_admin import BHHWhoIllnessAdmin
from .cancer_diagnosis_admin import CancerDiagnosisAdmin
from .enrollment_checklist_admin import EnrollmentChecklistAdmin
from .haart_record_admin import HaartRecordAdmin
from .lab_result_admin import LabResultAdmin, LabResultAdminMixin
# from .lab_result_cd4_admin import LabResultCd4Admin
from .lab_result_chemistry_admin import LabResultChemistryAdmin
from .lab_result_haemotology_admin import LabResultHaematologyAdmin
from .lab_result_height_weight_admin import LabResultHeightWeightAdmin
from .lab_result_hiv_admin import LabResultHivAdmin
from .lab_result_tb_admin import LabResultTbAdmin
from .lab_result_viralload_admin import LabResultViralloadAdmin
from .onschedule_admin import OnScheduleAdmin
from .otr_chemo_admin import OTRChemoAdmin
# from .otr_radiation_admin import OTRRadiationAdmin
from .otr_surgical_form import OTRSurgicalAdmin
from .oncology_treatment_plan_admin import OncologyTreatmentPlanAdmin
from .activity_and_functioning_admin import ActivityAndFunctioningAdmin
# from .main import HaartRecordAdmin, OncologyTreatmentPlanAdmin, TreatmentResponseAdmin
# from .main import SymptomsAndTestingAdmin, OncologyTreatmentCompletedAdmin
# from .main import CurrentSymptomsAdmin
# from .oncology_treatment_record_admin import OncologyTreatmentRecordAdmin, OTRChemoAdmin
# from .oncology_treatment_record_admin import OTRRadiationAdmin, OTRSurgicalAdmin
from .radiation_treatment_admin import RadiationTreatmentAdmin
from .subject_consent_admin import SubjectConsentAdmin
from .subject_locator_admin import SubjectLocatorAdmin
from .subject_offstudy_admin import SubjectOffStudyAdmin
from .subject_visit_admin import SubjectVisitAdmin
from .symptoms_and_testing_admin import SymptomsAndTestingAdmin
