# Generated by Django 2.0b1 on 2017-10-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_subject', '0002_historicalsubjecteligibility_subjecteligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjecteligibility',
            name='inability_to_participate',
            field=models.CharField(choices=[('able', 'ABLE to participate'), ('Mental Incapacity', 'Mental Incapacity'), ('Deaf/Mute', 'Deaf/Mute'), ('Too sick', 'Too sick'), ('Incarcerated', 'Incarcerated'), ('OTHER', 'Other, specify.'), ('N/A', 'Not applicable')], default=None, help_text='Participant can only participate if NONE is selected. (Any of these reasons make the participant unable to take part in the informed consent process)', max_length=17, verbose_name='Do any of the following reasons apply to the participant?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjecteligibility',
            name='inability_to_participate',
            field=models.CharField(choices=[('able', 'ABLE to participate'), ('Mental Incapacity', 'Mental Incapacity'), ('Deaf/Mute', 'Deaf/Mute'), ('Too sick', 'Too sick'), ('Incarcerated', 'Incarcerated'), ('OTHER', 'Other, specify.'), ('N/A', 'Not applicable')], default=None, help_text='Participant can only participate if NONE is selected. (Any of these reasons make the participant unable to take part in the informed consent process)', max_length=17, verbose_name='Do any of the following reasons apply to the participant?'),
            preserve_default=False,
        ),
    ]
