# Generated by Django 2.0b1 on 2017-10-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_subject', '0005_auto_20171027_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='screening_identifier',
            field=models.CharField(default=None, max_length=50, verbose_name='Screening Identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='screening_identifier',
            field=models.CharField(default=None, max_length=50, verbose_name='Screening Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalsubjectconsent',
            name='language',
            field=models.CharField(choices=[('tn', 'Setswana'), ('en', 'English')], help_text='The language used for the edc_consent process will also be used during data collection.', max_length=25, verbose_name='Language of consent'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='language',
            field=models.CharField(choices=[('tn', 'Setswana'), ('en', 'English')], help_text='The language used for the edc_consent process will also be used during data collection.', max_length=25, verbose_name='Language of consent'),
        ),
    ]
