# Generated by Django 2.0b1 on 2017-10-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_subject', '0006_auto_20171027_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectconsent',
            name='screening_identifier',
        ),
        migrations.RemoveField(
            model_name='subjectconsent',
            name='screening_identifier',
        ),
    ]
