# Generated by Django 2.0b1 on 2017-11-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_subject', '0009_ae010_af004_historicalsubjectoffstudy_subjectoffstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='slug',
            field=models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='slug',
            field=models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
    ]
