# Generated by Django 2.0b1 on 2017-11-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_subject', '0010_auto_20171102_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentchecklist',
            name='slug',
            field=models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historicalenrollmentchecklist',
            name='slug',
            field=models.CharField(db_index=True, default='', editable=False, help_text='a field used for quick search', max_length=250, null=True),
        ),
    ]
